"""Initial migration with user_id in Trip

Revision ID: 31ccea342b50
Revises: 
Create Date: 2025-07-26 03:22:21.920393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ccea342b50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('username')

    op.create_table('_alembic_tmp_trip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('destination', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_trip_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
